---
- hosts: all
  connection: local
  tasks:
    - name: test
      date:
    - name: 引数あり
      greet: name="Foo"
    - name: 引数なし
      greet:
    - name: cmd
      cmd: user=sysadmin password=sysadmin address={{ inventory_hostname }}
    - name: get remote host ip address
      command: echo {{ inventory_hostname }}
